version: '3'

services:
  mysql:
    image: mysql
    container_name: im-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zero_im
    ports:
      - "13306:3306"
    networks:
      - zero-im
  redis:
    image: redis
    container_name: im-redis
    restart: always
    ports:
      - "16379:6379"
    networks:
      - zero-im
  etcd:
    image: quay.io/coreos/etcd
    container_name: im-etcd
    restart: always
    ports:
      - "12379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes

networks:
    zero-im:
        driver: bridge